# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true

  config.vm.define "master-01" do |node|
      node.vm.box = "bento/rockylinux-10"
      node.vm.box_version = "202512.01.0"
      node.vm.hostname = "master-01"
      node.vm.network "private_network", ip: "192.168.33.10"

      config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = "1"
      end
  end

  config.vm.define "worker-01" do |node|
      node.vm.box = "bento/rockylinux-10"
      node.vm.box_version = "202512.01.0"
      node.vm.hostname = "worker-01"
      node.vm.network "private_network", ip: "192.168.33.11"
      config.vm.provider "virtualbox" do |vb|
        vb.memory = "8192"
        vb.cpus = "4"
      end
  end
end
